#!/bin/bash

echo ""
echo "## destroying containers"
echo ""

docker rm -f demo-badguy
docker rm -f demo-admin
docker rm -f demo-server

echo ""
echo "## destroying the switch"
echo ""

sudo ovs-vsctl del-br demosw

echo "done"
echo ""
